<script lang="ts">
  import baseline from '../../data/baseline_corpus_results.json';
  import { tokenizerHue } from '../utils/coloring';

  interface Cell {
    tokenCount: number;
    bytesPerToken: number;
  }
  type Metric = 'tokenCount' | 'bytesPerToken';

  let metric = $state<Metric>('tokenCount');

  const matrix = baseline.matrix as unknown as Record<
    string,
    Record<string, Cell | null>
  >;
  const tokenizers = baseline.tokenizers.filter((t) => t.loaded);
  const corpus = baseline.corpus;

  function cell(code: string, textId: string): Cell | null {
    return matrix[code]?.[textId] ?? null;
  }

  // Per-category min/max token counts, for heat shading and the ratio column.
  const stats = $derived.by(() => {
    const out: Record<string, { min: number; max: number }> = {};
    for (const c of corpus) {
      const vals = tokenizers
        .map((t) => cell(t.code, c.id)?.tokenCount)
        .filter((v): v is number => v != null);
      out[c.id] = { min: Math.min(...vals), max: Math.max(...vals) };
    }
    return out;
  });

  /** 0 (best) .. 1 (worst) within a category, for heat shading. */
  function heat(code: string, textId: string): number {
    const v = cell(code, textId)?.tokenCount;
    const s = stats[textId];
    if (v == null || !s || s.max === s.min) return 0;
    return (v - s.min) / (s.max - s.min);
  }

  function show(code: string, textId: string): string {
    const c = cell(code, textId);
    if (!c) return '—';
    return metric === 'tokenCount' ? String(c.tokenCount) : c.bytesPerToken.toFixed(2);
  }

  // Honest findings, recomputed from the committed data so they cannot drift.
  const findings = $derived.by(() => {
    const out: string[] = [];
    const zh = stats['zh'];
    if (zh) {
      out.push(
        `The shared passage in Chinese costs ${zh.max} tokens with the least ` +
          `efficient tokenizer and ${zh.min} with the most efficient — a ` +
          `${(zh.max / zh.min).toFixed(1)}x gap on identical content.`,
      );
    }
    // Swahili vs English on the same tokenizer (first available).
    const ref = tokenizers[0]?.code;
    const sw = ref ? cell(ref, 'sw')?.tokenCount : null;
    const en = ref ? cell(ref, 'en-prose')?.tokenCount : null;
    if (sw && en) {
      out.push(
        `With ${tokenizers[0].name}, the Swahili passage costs ` +
          `${(((sw - en) / en) * 100).toFixed(0)}% more tokens than the ` +
          `English one — a Latin-script language still penalised by training-data coverage.`,
      );
    }
    return out;
  });
</script>

<section class="rc">
  <div class="rc-head">
    <div>
      <span class="eyebrow">Reference corpus — precomputed</span>
      <p class="rc-sub">
        Every tokenizer over a fixed 10-text corpus. Generated by
        <code>scripts/precompute_baseline.ts</code>; no figure is hand-entered.
      </p>
    </div>
    <div class="metric-toggle">
      <button
        class:on={metric === 'tokenCount'}
        onclick={() => (metric = 'tokenCount')}
      >
        tokens
      </button>
      <button
        class:on={metric === 'bytesPerToken'}
        onclick={() => (metric = 'bytesPerToken')}
      >
        bytes / token
      </button>
    </div>
  </div>

  <div class="scroll-x">
    <table class="mono">
      <thead>
        <tr>
          <th class="corner">tokenizer</th>
          {#each corpus as c (c.id)}
            <th title={c.note}>{c.id}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each tokenizers as t (t.code)}
          <tr>
            <th class="rowh">
              <span class="key" style:background={tokenizerHue(t.code)}></span>{t.name}
            </th>
            {#each corpus as c (c.id)}
              <td class:lower={metric === 'tokenCount'} style:--h={heat(t.code, c.id)}>
                {show(t.code, c.id)}
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <ul class="findings">
    {#each findings as f (f)}
      <li>{f}</li>
    {/each}
  </ul>
  <p class="rc-gen">
    Generated {new Date(baseline.generatedAt).toISOString().slice(0, 10)} · js-tiktoken {baseline
      .libraries['js-tiktoken']} · @lenml/tokenizers {baseline.libraries[
      '@lenml/tokenizers'
    ]}
  </p>
</section>

<style>
  .rc {
    margin-top: 30px;
  }
  .rc-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
    margin-bottom: 11px;
    flex-wrap: wrap;
  }
  .rc-sub {
    margin: 4px 0 0;
    font-size: 12px;
    color: var(--text-dim);
    max-width: 60ch;
  }
  .rc-sub code {
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--text);
  }
  .metric-toggle {
    display: flex;
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    overflow: hidden;
  }
  .metric-toggle button {
    background: var(--bg-raised);
    border: none;
    padding: 5px 11px;
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--text-dim);
  }
  .metric-toggle button.on {
    background: var(--accent-soft);
    color: var(--accent);
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }
  th,
  td {
    padding: 6px 9px;
    border: 1px solid var(--border);
    text-align: right;
    white-space: nowrap;
  }
  thead th {
    color: var(--text-faint-solid);
    font-weight: 500;
    font-size: 10.5px;
  }
  .corner,
  .rowh {
    text-align: left;
    position: sticky;
    left: 0;
    background: var(--bg-raised);
  }
  .rowh {
    color: var(--text);
    font-weight: 500;
  }
  .key {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 2px;
    margin-right: 6px;
  }
  td {
    background: color-mix(
      in srgb,
      var(--warn) calc(var(--h, 0) * 26%),
      var(--bg-raised)
    );
    color: var(--text);
  }
  .findings {
    margin: 14px 0 0;
    padding-left: 18px;
  }
  .findings li {
    font-size: 12.5px;
    color: var(--text-dim);
    margin-bottom: 5px;
  }
  .rc-gen {
    margin: 9px 0 0;
    font-family: var(--font-mono);
    font-size: 10.5px;
    color: var(--text-faint-solid);
  }
</style>
