<script lang="ts">
  import baseline from '../../data/baseline_corpus_results.json';
  import { tokenizerHue } from '../utils/coloring';

  interface Cell {
    tokenCount: number;
    bytesPerToken: number;
  }
  type Metric = 'tokenCount' | 'bytesPerToken';

  let metric = $state<Metric>('tokenCount');

  const matrix = baseline.matrix as unknown as Record<
    string,
    Record<string, Cell | null>
  >;
  const tokenizers = baseline.tokenizers.filter((t) => t.loaded);
  const corpus = baseline.corpus;

  function cell(code: string, textId: string): Cell | null {
    return matrix[code]?.[textId] ?? null;
  }

  /** Per-category min/max for the currently shown metric. */
  const stats = $derived.by(() => {
    const out: Record<string, { min: number; max: number }> = {};
    for (const c of corpus) {
      const vals = tokenizers
        .map((t) => {
          const cl = cell(t.code, c.id);
          return cl ? cl[metric] : undefined;
        })
        .filter((v): v is number => v != null);
      out[c.id] = { min: Math.min(...vals), max: Math.max(...vals) };
    }
    return out;
  });

  /**
   * 0 (best) .. 1 (worst) within a category, used for heat shading.
   * For `tokenCount`, lower is better; for `bytesPerToken`, higher is better.
   */
  function heat(code: string, textId: string): number {
    const c = cell(code, textId);
    if (!c) return 0;
    const v = c[metric];
    const s = stats[textId];
    if (s.max === s.min) return 0;
    return metric === 'tokenCount'
      ? (v - s.min) / (s.max - s.min)
      : (s.max - v) / (s.max - s.min);
  }

  function show(code: string, textId: string): string {
    const c = cell(code, textId);
    if (!c) return '—';
    return metric === 'tokenCount' ? String(c.tokenCount) : c.bytesPerToken.toFixed(2);
  }

  // Honest findings, recomputed from the committed data so they cannot drift.
  const findings = $derived.by(() => {
    const out: string[] = [];
    // Findings sentences always quote token counts, regardless of the active
    // table metric — so compute them from tokenCount directly, not `stats`.
    const zhVals = tokenizers
      .map((t) => cell(t.code, 'zh')?.tokenCount)
      .filter((v): v is number => v != null);
    if (zhVals.length) {
      const zmin = Math.min(...zhVals);
      const zmax = Math.max(...zhVals);
      out.push(
        `The shared passage in Chinese costs ${zmax} tokens with the least ` +
          `efficient tokenizer and ${zmin} with the most efficient — a ` +
          `${(zmax / zmin).toFixed(1)}x gap on identical content.`,
      );
    }
    // Swahili vs English on the same tokenizer (first available).
    const ref = tokenizers[0]?.code;
    const sw = ref ? cell(ref, 'sw')?.tokenCount : null;
    const en = ref ? cell(ref, 'en-prose')?.tokenCount : null;
    if (sw && en) {
      out.push(
        `With ${tokenizers[0].name}, the Swahili passage costs ` +
          `${(((sw - en) / en) * 100).toFixed(0)}% more tokens than the ` +
          `English one — a Latin-script language still penalised by training-data coverage.`,
      );
    }
    // OpenAI's own progression on Chinese — the cl100k → o200k step is the
    // single biggest multilingual-fairness improvement in the GPT family.
    const gpt2zh = cell('gpt2', 'zh')?.tokenCount;
    const o200kzh = cell('o200k', 'zh')?.tokenCount;
    if (gpt2zh && o200kzh) {
      out.push(
        `Within OpenAI alone, the GPT-2 → o200k progression cut the Chinese ` +
          `passage from ${gpt2zh} tokens to ${o200kzh} — a ` +
          `${(((gpt2zh - o200kzh) / gpt2zh) * 100).toFixed(0)}% drop across ` +
          `tokenizer generations, with no model change.`,
      );
    }
    return out;
  });
</script>

<section class="rc" aria-labelledby="rc-h">
  <div class="rc-head">
    <div>
      <h2 id="rc-h" class="eyebrow">Reference corpus — precomputed</h2>
      <p class="rc-sub">
        Every tokenizer over a fixed 10-text corpus. Generated by
        <code>scripts/precompute_baseline.ts</code>; no figure is hand-entered.
      </p>
    </div>
    <div class="metric-toggle" role="radiogroup" aria-label="Reference-corpus metric">
      <button
        role="radio"
        aria-checked={metric === 'tokenCount'}
        class:on={metric === 'tokenCount'}
        onclick={() => (metric = 'tokenCount')}
      >
        tokens
      </button>
      <button
        role="radio"
        aria-checked={metric === 'bytesPerToken'}
        class:on={metric === 'bytesPerToken'}
        onclick={() => (metric = 'bytesPerToken')}
      >
        bytes / token
      </button>
    </div>
  </div>

  <div class="scroll-x">
    <table class="mono">
      <thead>
        <tr>
          <th class="corner" scope="col">tokenizer</th>
          {#each corpus as c (c.id)}
            <th scope="col" title={c.note}>{c.id}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each tokenizers as t (t.code)}
          <tr>
            <th class="rowh" scope="row">
              <span
                class="key"
                style:background={tokenizerHue(t.code)}
                aria-hidden="true"
              ></span>{t.name}
            </th>
            {#each corpus as c (c.id)}
              <td class:lower={metric === 'tokenCount'} style:--h={heat(t.code, c.id)}>
                {show(t.code, c.id)}
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <ul class="findings">
    {#each findings as f (f)}
      <li>{f}</li>
    {/each}
  </ul>
  <p class="rc-gen">
    Generated {new Date(baseline.generatedAt).toISOString().slice(0, 10)} · js-tiktoken {baseline
      .libraries['js-tiktoken']} · @lenml/tokenizers {baseline.libraries[
      '@lenml/tokenizers'
    ]}
  </p>
</section>

<style>
  .rc {
    margin-top: 30px;
  }
  .rc-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
    margin-bottom: 11px;
    flex-wrap: wrap;
  }
  .rc-sub {
    margin: 4px 0 0;
    font-size: 12px;
    color: var(--text-dim);
    max-width: 60ch;
  }
  .rc-sub code {
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--text);
  }
  .metric-toggle {
    display: flex;
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    overflow: hidden;
  }
  .metric-toggle button {
    background: var(--bg-raised);
    border: none;
    padding: 7px 12px;
    min-height: 32px;
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--text-dim);
  }
  @media (max-width: 600px) {
    .metric-toggle button {
      min-height: 40px;
      padding: 10px 14px;
    }
  }
  .metric-toggle button.on {
    background: var(--accent-soft);
    color: var(--accent);
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }
  th,
  td {
    padding: 6px 9px;
    border: 1px solid var(--border);
    text-align: right;
    white-space: nowrap;
  }
  thead th {
    color: var(--text-faint-solid);
    font-weight: 500;
    font-size: 10.5px;
  }
  .corner,
  .rowh {
    text-align: left;
    position: sticky;
    left: 0;
    background: var(--bg-raised);
  }
  .rowh {
    color: var(--text);
    font-weight: 500;
  }
  .key {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 2px;
    margin-right: 6px;
  }
  td {
    background: color-mix(
      in srgb,
      var(--warn) calc(var(--h, 0) * 26%),
      var(--bg-raised)
    );
    color: var(--text);
  }
  .findings {
    margin: 14px 0 0;
    padding-left: 18px;
  }
  .findings li {
    font-size: 12.5px;
    color: var(--text-dim);
    margin-bottom: 5px;
  }
  .rc-gen {
    margin: 9px 0 0;
    font-family: var(--font-mono);
    font-size: 10.5px;
    color: var(--text-faint-solid);
  }
</style>
