/**
 * Runs every tokenizer over the standardized corpus and writes
 * `data/baseline_corpus_results.json`. This file is the sole source of the
 * numbers shown in the app's reference table — nothing is hand-entered.
 *
 * Run with `npm run precompute` (requires `npm run setup` first).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { TokenizerEngine } from '../src/tokenizers/engine';
import { TOKENIZERS } from '../src/tokenizers/registry';
import { byteLength } from '../src/tokenizers/base';
import { loadAssetsFromFs, ROOT } from './node_assets';

interface CorpusText {
  id: string;
  category: string;
  language: string;
  note: string;
  text: string;
}

async function pkgVersion(name: string): Promise<string> {
  const p = join(ROOT, 'node_modules', name, 'package.json');
  return JSON.parse(await readFile(p, 'utf8')).version as string;
}

async function main() {
  const corpus = JSON.parse(
    await readFile(join(ROOT, 'data', 'baseline_corpus.json'), 'utf8'),
  ) as { texts: CorpusText[] };
  const texts = corpus.texts;

  const engine = new TokenizerEngine();
  const loaded: string[] = [];
  for (const spec of TOKENIZERS) {
    try {
      engine.load(spec.code, await loadAssetsFromFs(spec.code));
      loaded.push(spec.code);
      console.log(`loaded ${spec.code}`);
    } catch (err) {
      console.error(`FAILED to load ${spec.code}: ${(err as Error).message}`);
    }
  }

  const matrix: Record<string, Record<string, unknown>> = {};
  let roundtripFailures = 0;

  for (const spec of TOKENIZERS) {
    matrix[spec.code] = {};
    for (const t of texts) {
      if (!engine.isLoaded(spec.code)) {
        matrix[spec.code][t.id] = null; // honest "—" in the UI
        continue;
      }
      const r = engine.run(t.text, spec.code);
      if (r.error) {
        console.error(`  ${spec.code}/${t.id}: ${r.error}`);
        matrix[spec.code][t.id] = null;
        continue;
      }
      const tokenCount = r.tokens.length;
      const byteCount = r.byteLength;
      const charCount = r.charLength;

      // Byte-roundtrip sanity check for lossless (byte-level BPE) tokenizers.
      if (spec.algorithm === 'byte-level BPE') {
        const total = r.tokens.reduce((n, tok) => n + tok.bytes.length, 0);
        if (total !== byteCount) {
          roundtripFailures++;
          console.error(
            `  ROUNDTRIP MISMATCH ${spec.code}/${t.id}: token bytes ${total} != input bytes ${byteCount}`,
          );
        }
      }

      matrix[spec.code][t.id] = {
        tokenCount,
        byteCount,
        charCount,
        bytesPerToken: +(byteCount / tokenCount).toFixed(3),
        charsPerToken: +(charCount / tokenCount).toFixed(3),
      };
    }
  }

  const out = {
    generatedAt: new Date().toISOString(),
    note: 'Generated by scripts/precompute_baseline.ts. Do not edit by hand.',
    libraries: {
      'js-tiktoken': await pkgVersion('js-tiktoken'),
      '@lenml/tokenizers': await pkgVersion('@lenml/tokenizers'),
    },
    corpus: texts.map((t) => ({
      id: t.id,
      category: t.category,
      language: t.language,
      note: t.note,
      byteLength: byteLength(t.text),
    })),
    tokenizers: TOKENIZERS.map((s) => ({
      code: s.code,
      name: s.name,
      family: s.family,
      algorithm: s.algorithm,
      loaded: loaded.includes(s.code),
    })),
    matrix,
  };

  const dest = join(ROOT, 'data', 'baseline_corpus_results.json');
  await writeFile(dest, JSON.stringify(out, null, 2) + '\n');
  console.log(`\nWrote ${dest}`);
  console.log(`Loaded ${loaded.length}/${TOKENIZERS.length} tokenizers.`);
  if (roundtripFailures > 0) {
    console.error(
      `${roundtripFailures} byte-roundtrip failures — investigate before shipping.`,
    );
    process.exitCode = 1;
  } else {
    console.log('All byte-level roundtrip checks passed.');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
